### ISSUE TITLE
Register symmetric key sample code Timeout

### ISSUE THREAD

**Issue by taak77** [Azure/azure-iot-sdk-python-preview#112]
* Mac 10.14
* Python 3.7.3
* Azure IoT Device 2.0.0rc6
* Installed Python packages (pip3 freeze output)

```
applicationinsights==0.11.7
arrow==0.13.1
asn1crypto==0.24.0
astroid==2.1.0
aws-lambda-builders==0.2.1
aws-sam-cli==0.14.1
aws-sam-translator==1.10.0
aws-shell==0.2.1
awscli==1.16.24
azure-iot-device==2.0.0rc6
bcrypt==3.1.6
binaryornot==0.4.4
boto3==1.9.122
botocore==1.12.122
cached-property==1.5.1
certifi==2019.3.9
cffi==1.12.0
chardet==3.0.4
chevron==0.13.1
click==6.7
colorama==0.3.9
configobj==5.0.6
cookiecutter==1.6.0
cryptography==2.5
cycler==0.10.0
dateparser==0.7.1
decorator==4.3.2
docker==3.7.0
docker-compose==1.23.2
docker-pycreds==0.4.0
dockerpty==0.4.1
docopt==0.6.2
docutils==0.14
Flask==1.0.2
future==0.17.1
GDAL==2.4.0
idna==2.8
iotedgehubdev==0.8.0
isort==4.3.4
itsdangerous==1.1.0
janus==0.4.0
Jinja2==2.10
jinja2-time==0.2.0
jmespath==0.9.3
jsonpath-rw==1.4.0
jsonschema==2.6.0
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
MarkupSafe==1.1.1
matplotlib==3.0.3
mccabe==0.6.1
nose==1.3.7
numpy==1.16.1
paho-mqtt==1.4.0
pandas==0.24.2
paramiko==2.4.2
ply==3.11
poyo==0.4.2
prompt-toolkit==1.0.15
pyasn1==0.4.4
pycparser==2.19
Pygments==2.2.0
pylint==2.2.2
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.0
python-dateutil==2.7.3
pytz==2018.9
PyYAML==3.13
regex==2019.3.12
requests==2.22.0
requests-unixsocket==0.1.5
rsa==3.4.2
s3transfer==0.2.0
serverlessrepo==0.1.8
six==1.12.0
texttable==0.9.1
transitions==0.6.9
tzlocal==1.5.1
urllib3==1.24.3
wcwidth==0.1.7
websocket-client==0.54.0
Werkzeug==0.15.1
whichcraft==0.5.2
wrapt==1.11.1
```

I'm getting the following error from device registration with symmetric key sample to register device (https://github.com/Azure/azure-iot-sdk-python-preview/blob/release_2019_06_09/azure-iot-device/samples/advanced-hub-scenarios/register_symmetric_key.py)

```
DEBUG:asyncio:Using selector: KqueueSelector
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRoot(SetSymmetricKeySecurityClient): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRoot(SetSymmetricKeySecurityClient): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSymmetricKeySecurityClient(SetSymmetricKeySecurityClient): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSymmetricKeySecurityClient(SetSymmetricKeySecurityClientArgs):run_ops_serial: starting first op.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSymmetricKeySecurityClient(SetSymmetricKeySecurityClientArgs): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(SetSymmetricKeySecurityClientArgs): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(SetSymmetricKeySecurityClientArgs): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverter(SetSymmetricKeySecurityClientArgs): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverter(SetSymmetricKeySecurityClientArgs): continuing with SetConnectionArgs op
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverter(SetConnectionArgs): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:Provider(SetConnectionArgs): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:Provider(SetConnectionArgs): got connection args
INFO:azure.iot.device.common.mqtt_provider:creating mqtt client
INFO:azure.iot.device.common.mqtt_provider:Created MQTT provider, assigned callbacks
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:Provider(SetConnectionArgs): completing without error
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverter(SetSymmetricKeySecurityClientArgs): completing with result from SetConnectionArgs
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverter(SetSymmetricKeySecurityClientArgs): completing without error
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSymmetricKeySecurityClient(SetSymmetricKeySecurityClientArgs):run_ops_serial: completed. 1 items left
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSymmetricKeySecurityClient(SetSymmetricKeySecurityClientArgs):run_ops_serial: op succeeded. running next op in list.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSymmetricKeySecurityClient(SetSasToken): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(SetSasToken): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(SetSasToken): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverter(SetSasToken): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverter(SetSasToken): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:Provider(SetSasToken): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:Provider(SetSasToken): got password
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:Provider(SetSasToken): completing without error
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSymmetricKeySecurityClient(SetSasToken):run_ops_serial: completed. 0 items left
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSymmetricKeySecurityClient(SetSasToken):run_ops_serial: last op succeeded.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSymmetricKeySecurityClient(SetSasToken):run_ops_serial: no finally_op.  calling back.
INFO:azure.iot.device.provisioning.aio.async_sk_provisioning_device_client:Registering with Hub...
INFO:azure.iot.device.provisioning.internal.polling_machine:register called from polling machine
DEBUG:transitions.core:Initiating transition from state disconnected to state initializing...
INFO:azure.iot.device.provisioning.internal.polling_machine:Initializing the registration process.
INFO:azure.iot.device.provisioning.pipeline.provisioning_pipeline:enable_responses called
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRoot(EnableFeature): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRoot(EnableFeature): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSymmetricKeySecurityClient(EnableFeature): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:UseSymmetricKeySecurityClient(EnableFeature): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(EnableFeature): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(EnableFeature): enabling block
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(EnableFeature): queueing until connection complete
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(EnableFeature): calling down with Connect operation
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(Connect): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverter(Connect): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:ProvisioningMQTTConverter(Connect): passing to next stage.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:Provider(Connect): running
INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:Provider(Connect): conneting
INFO:azure.iot.device.common.mqtt_provider:connecting to mqtt broker
ERROR:azure.iot.device.common.pipeline.pipeline_stages_base:Error in <azure.iot.device.common.pipeline.pipeline_stages_mqtt.Provider object at 0x107df24a8>._run_op() call
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 94, in run_op
    self._run_op(op)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 88, in _run_op
    raise e
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 85, in _run_op
    self.provider.connect(self.sas_token)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_provider.py", line 144, in connect
    self._mqtt_client.connect(host=self._hostname, port=8883)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:Provider(Connect): completing with error
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(EnableFeature): connection is complete
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(EnableFeature): disabling block and releasing queued ops.
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(EnableFeature): processing 1 items in queue
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(EnableFeature): failing EnableFeature op because of error
INFO:azure.iot.device.common.pipeline.pipeline_stages_base:EnsureConnection(EnableFeature): completing with error
INFO:azure.iot.device.provisioning.internal.polling_machine:Transition complete.  Trigger=_trig_register, Src=disconnected, Dest=initializing, result=False, errorNone
DEBUG:transitions.core:Executed machine finalize callback '<function PollingMachine.__init__.<locals>._on_transition_complete at 0x107e05400>'.
```

registration_id: 825107f0cb6e4dde896f7efe6bb1e803
symmetric_key: y1viKk770NF801OzG96pq1ehI+npsvGlhyaVSZHVqd0=

Does anyone have any idea?
Thank you in advance.

**Comment by olivakar** [comment]
I tried the sample with my values in Mac (10.14.4) with Python (3.7.0) and it works. I would still like to get hold of the values of the following environment variables that are getting used in your sample to try.

- PROVISIONING_HOST
- PROVISIONING_IDSCOPE
- REGISTRATION_ID
- SYMMETRIC_KEY

You can provide these details by other means and not in clear text on this issue page.
To ensure that your previous key is still safe please generate your symmetric key again.
You can also delete the enrollment completely to be on the safe side.

**Comment by taak77** [comment]
@olivakar Thanks for verifying. I would like to provide you with all the env variables you mentioned, how would you recommend for me to provide those information?

**Comment by olivakar** [comment]
If you sign in to GitHub you should be able to see my email. You can send via that.

**Comment by pierreca** [comment]
@taak77 @olivakar The best way to send us confidential data is through a support request. 

Every customer with an active Azure subscription has access to [support](https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request) with guaranteed response time.  

In the support request, please mention this github issue, the fact that it's related to the Python SDK and "Oliva Kar" and the support engineer should know to reach out and pass along the information in a secure way.

**Comment by taak77** [comment]
@olivakar @pierreca thank you for your response and apology for the late reply, I have figured out the issue, it was due to `symmetric_key` not properly stringified, after the fix on my end, the functionality works now! I'll close the issue. Thanks again.
