### ISSUE TITLE
get_twin_x509.py error "SSL/TLS has already been configured"

### ISSUE THREAD

**Issue by bukarev** [Azure/azure-iot-sdk-python-preview#143]
I've successfully registered a device using group enrollment with x509 certificates, and have been able to run the scripts from this SDK for a few days.
But suddenly the script get_twin_x509.py stopped working. The error it cites is:
`
future: <Task finished coro=<main.<locals>.twin_patch_listener() done, defined at get_twin_x509.py:42> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 94, in run_op
    self._run_op(op)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 104, in _run_op
    raise e
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 100, in _run_op
    password=self.sas_token, client_certificate=self.trusted_certificate_chain
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 157, in connect
    self._mqtt_client.tls_set_context(context=ssl_context)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 688, in tls_set_context
    raise ValueError('SSL/TLS has already been configured.')
ValueError: SSL/TLS has already been configured.
`

The system in question is Raspbian, Python 3.7.4

**Comment by bukarev** [comment]
Oh, apparently the script setting env variables with certificate file paths was outdated.
